### ISSUE TITLE
The tradeoff between autorelease object and smart pointers

### ISSUE THREAD

**Issue by KaoCC** [GPUOpen-LibrariesAndSDKs/RadeonProRender-Baikal#43]
Hi there. I really love this project and I sincerely appreciate your hard work.

However, I got one little question:

In the class `Scene1` , is there any reason not to use a smart pointer, such as `std::unique_ptr`, to handle all the resources such as Shapes and Lights in the class design ? Is there any benefit or performance impact of using autorelease pool ?

Thank you very much for your reply.

**Comment by yozhijk** [comment]
Hi @KaoCC ,

Thank you:) std::unique_ptr wouldn't work in this case because the ownership is shared between the API user and internals of the engine, but shared_ptr would work perfectly. I actually even have a pending pull request which does just that, but unfortunately did not have time to merge yet. But stay tuned, we will do that shortly.

**Comment by yozhijk** [comment]
Hi @KaoCC ,

Smart pointers was implemented here: https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRender-Baikal/commit/bbb02c8350059a1d5bc071dd23d47423fc6d26de
